### PR TITLE
Curl: retry requests to the endpoint

### LINKED ISSUE #16: Feature discussion: Retry HTTP request in cases of bad response from esplora
Hi,

Before all, I want say if this issue contains some stupid affirmation, please close it :)

Today I pass several time to test esplora on my "server" and I received an error descrived inside this issue #15.

before to open the issue I made some test on my branch and I make some consideration, such as:

- esplora plugin is designed to fetch all data from esplora, it mean that it should make a lot of http connection. In most of the cases and at this moment this plugin is very useful to permit to run c-lightning on small devices, such as raspberry (without some special configuration) or Android devices. With this introduction, I list the possible problem that I can happenend:
   - Small devices can be connected to not good connections, this event can cause some errors such as connection error (i.e. switch network on devices, lost connection on devices for few seconds). Wiht this problem and c-lightning marked some plugin such as important plugin with this PR https://github.com/ElementsProject/lightning/pull/3890.
At this point some error inside the http request can bring the lightningd to crash. This is not a big problem because you can restart it but this can be frustrating in some cases.

The solution that I want propose, is the same that bcli has inside the code when the bitcoind is not ready. It wait a few second and retries the connection. I think is good to have this function also in esplora plugin?

What do you think?

### PR DESCRIPTION
**Pull request by darosior**
This is an alternative to #26 (closes #26), in order to fix #16.

Turns out i made a few other drive-by changes, but i think it was worth it :).

Summary:
- we now retry curl request multiple times (4 by default)
- new startup option `esplora-retries` which conditions how many times we'll retry a request.
- the startup option `verbose` now takes a boolean (breaking change!)
- small cleanups here and there.

### CODE REVIEW

File: esplora.c [hunk 1]
```diff
@@ -74,46 +85,63 @@ static size_t write_memory_callback(void *contents, size_t size, size_t nmemb,
...
+	u32 retries = 0;
+
+	for (;;) {
+		res = curl_easy_perform(curl);
+		if (res == CURLE_OK)
+			return true;
+
+		if (++retries > esplora->n_retries)
+			return false;
+		sleep(1);
```
Comment (vincenzopalazzo) [inline esplora.c:101]: Only one comment about the time, because do you think that it is a good time 1 second? This can resolve the problem with the fee rate unavailable with esplora?

The log result with 1 minutes is reported below;

```
2020-08-30T17:00:04.028Z INFO plugin-esplora: getrawblockbyheight 1830250
2020-08-30T17:00:04.028Z DEBUG plugin-esplora: bad code in the info answare! wait 60 before retry
2020-08-30T17:00:04.028Z DEBUG plugin-esplora: 1: Retry info request to URL=https://blockstream.info/testnet/api/block-height/1830250
2020-08-30T17:00:04.029Z DEBUG plugin-esplora: bad code in the info answare! wait 60 before retry
2020-08-30T17:00:04.029Z DEBUG plugin-esplora: 2: Retry info request to URL=https://blockstream.info/testnet/api/block-height/1830250
2020-08-30T17:00:04.029Z DEBUG plugin-esplora: bad code in the info answare! wait 60 before retry
2020-08-30T17:00:04.029Z DEBUG plugin-esplora: 3: Retry info request to URL=https://blockstream.info/testnet/api/block-height/1830250
2020-08-30T17:00:04.029Z DEBUG plugin-esplora: bad code in the info answare! wait 60 before retry
2020-08-30T17:00:04.029Z DEBUG plugin-esplora: 4: Retry info request to URL=https://blockstream.info/testnet/api/block-height/1830250
2020-08-30T17:00:04.106Z DEBUG lightningd: ... polled feerate estimate for min_acceptable (44) smoothed to 161 (alpha=0.44)
2020-08-30T17:00:04.106Z DEBUG lightningd: ... feerate estimate for min_acceptable hit floor 253
2020-08-30T17:00:15.558Z DEBUG gossipd: seeker: no peers, waiting
2020-08-30T17:00:40.447Z INFO plugin-esplora: getrawblockbyheight 1830250
2020-08-30T17:00:40.447Z INFO plugin-esplora: blockhash: 0000000000000c09139c4c018108edd0a6ff28f048a44565ceae5451bb7fb5f1 from https://blockstream.info/testnet/api/block-height/1830250
2020-08-30T17:00:40.447Z DEBUG lightningd: Adding block 1830250: 0000000000000c09139c4c018108edd0a6ff28f048a44565ceae5451bb7fb5f1
2020-08-30T17:00:40.532Z DEBUG lightningd: ... polled feerate estimate for min_acceptable (44) smoothed to 161 (alpha=0.44)
2020-08-30T17:00:40.532Z DEBUG lightningd: ... feerate estimate for min_acceptable hit floor 253
2020-08-30T17:00:43.922Z INFO plugin-esplora: getrawblockbyheight 1830251
2020-08-30T17:00:43.922Z INFO plugin-esplora: blockhash: 0000000000000dd4fee80e26c88955a9379d9fd5ef9782ec05b6edf854708469 from https://blockstream.info/testnet/api/block-height/1830251
2020-08-30T17:00:43.922Z DEBUG lightningd: Adding block 1830251: 0000000000000dd4fee80e26c88955a9379d9fd5ef9782ec05b6edf854708469
2020-08-30T17:00:49.653Z INFO plugin-esplora: getrawblockbyheight 1830252
2020-08-30T17:00:49.653Z INFO plugin-esplora: blockhash: 0000000000000b401c8fa5c493a04b372a83ee940c07d103c46247f209771b4f from https://blockstream.info/testnet/api/block-height/1830252
2020-08-30T17:00:49.656Z DEBUG lightningd: Adding block 1830252: 0000000000000b401c8fa5c493a04b372a83ee940c07d103c46247f209771b4f
2020-08-30T17:01:15.561Z DEBUG gossipd: seeker: no peers, waiting
2020-08-30T17:02:15.617Z DEBUG gossipd: seeker: no peers, waiting
2020-08-30T17:03:15.673Z DEBUG gossipd: seeker: no peers, waiting
2020-08-30T17:04:15.730Z DEBUG gossipd: seeker: no peers, waiting
2020-08-30T17:04:56.077Z INFO plugin-esplora: getrawblockbyheight 1830253
2020-08-30T17:04:56.077Z DEBUG plugin-esplora: bad code in the info answare! wait 60 before retry
2020-08-30T17:04:56.077Z DEBUG plugin-esplora: 1: Retry info request to URL=https://blockstream.info/testnet/api/block-height/1830253
2020-08-30T17:04:56.077Z DEBUG plugin-esplora: bad code in the info answare! wait 60 before retry
2020-08-30T17:04:56.077Z DEBUG plugin-esplora: 2: Retry info request to URL=https://blockstream.info/testnet/api/block-height/1830253
2020-08-30T17:04:56.077Z DEBUG plugin-esplora: bad code in the info answare! wait 60 before retry
2020-08-30T17:04:56.077Z DEBUG plugin-esplora: 3: Retry info request to URL=https://blockstream.info/testnet/api/block-height/1830253
2020-08-30T17:04:56.078Z DEBUG plugin-esplora: bad code in the info answare! wait 60 before retry
2020-08-30T17:04:56.078Z DEBUG plugin-esplora: 4: Retry info request to URL=https://blockstream.info/testnet/api/block-height/1830253
2020-08-30T17:04:56.151Z DEBUG lightningd: ... polled feerate estimate for min_acceptable (42) smoothed to 160 (alpha=0.44)
2020-08-30T17:04:56.151Z DEBUG lightningd: ... feerate estimate for min_acceptable hit floor 253

```

File: esplora.c [hunk 2]
```diff
@@ -523,22 +569,28 @@ static const struct plugin_command commands[] = {
...
+		    plugin_option("esplora-capath", "string",
+				  "Specify directory holding CA certificates.",
+				  charp_option, &esplora->capath),
+		    plugin_option("esplora-verbose", "bool",
+				  "Set verbose output (default: false).",
+				  bool_option, &esplora->verbose),
+		    plugin_option("esplora-retries", "int",
+				  "How many times should we retry a request to the"
+				  "endpoint before dying ?", u32_option, &esplora->n_retries),
+		    NULL);
```
Comment (vincenzopalazzo) [inline esplora.c:595]: Do you think is a good feature has another option to set the wait time?

File: esplora.c (hunk 1 above)
Comment (darosior) [reply esplora.c:101]: This won't resolve the testnet feerate issue: this is a network issue, there are not enough transactions made on testnet and bitcoind fee estimation buckets can not be filled.

That said, i find it too long already but kept it simple with a sleep().

File: esplora.c [hunk 3]
```diff
@@ -506,6 +534,24 @@ static void init(struct plugin *p, const char *buffer UNUSED,
...
 
+static struct esplora *new_esplora(const tal_t *ctx)
+{
+	struct esplora *esplora = tal(ctx, struct esplora);
+
+	esplora.endpoint = NULL;
+	esplora.capath = NULL;
+	esplora.cainfo_path = NULL;
+	esplora.verbose = false;
+	esplora.n_retries = 4;
```
Comment (vincenzopalazzo) [inline esplora.c:545]: I tried to compile this PR but I receive an error! Maybe here is correct use the `->` operator?

**Comment by darosior** [comment]
Arf i messed up the rebase .. Correcting now

File: esplora.c (hunk 3 above)
Comment (darosior) [reply esplora.c]: Thanks, it was in fact duplicated due to a rebase mistake.

File: esplora.c [hunk 4]
```diff
@@ -21,10 +21,21 @@
...
+	char *cainfo_path;
+	char *capath;
+
+	/* Make curl request more verbose. */
+	bool verbose;
+
+	/* How many times do we retry curl requests ? */
+	u32 n_retries;
+};
+static struct esplora *esplora;
```
Comment (lvaccaro) [inline esplora.c:38]: thanks, I really appreciate with struct 👍

File: esplora.c (hunk 2 above)
Comment (lvaccaro) [reply esplora.c:590]: good catch as improvements, we will enjoy to break the @darosior implementation XD (in another PR)

**Comment by lvaccaro** [comment]
ack d007a4515d951237109e3ed976a5313207feeac8

thanks, I really appreciate with struct 👍

nit: maybe I am doing something wrong, on debugging it looks like the default retries value is set to 0 instead 4, if I not pass the `esplora-retries` option.

**Comment by darosior** [comment]
> maybe I am doing something wrong, on debugging it looks like the default retries value is set to 0 instead 4, if I not pass the esplora-retries option.

Thanks for testing, will verify

**Comment by darosior** [comment]
lol, passing it as string actually fixed it.... Guess it's a bug report for lightningd then !
```patch
diff --git a/plugins/esplora.c b/plugins/esplora.c
index f3dbebf2f..9a12736b2 100644
--- a/plugins/esplora.c
+++ b/plugins/esplora.c
@@ -531,7 +531,7 @@ static struct command_result *sendrawtransaction(struct command *cmd,
 
 static void init(struct plugin *p, const char *buffer UNUSED,
                  const jsmntok_t *config UNUSED) {
-  plugin_log(p, LOG_INFORM, "esplora initialized.");
+  plugin_log(p, LOG_INFORM, "esplora initialized. %u", esplora->n_retries);
 }
 
 static struct esplora *new_esplora(const tal_t *ctx)
@@ -584,7 +584,7 @@ int main(int argc, char *argv[]) {
                    plugin_option("esplora-verbose", "bool",
                                  "Set verbose output (default: false).",
                                  bool_option, &esplora->verbose),
-                   plugin_option("esplora-retries", "int",
+                   plugin_option("esplora-retries", "string",
                                  "How many times should we retry a request to the"
                                  "endpoint before dying ?", u32_option, &esplora->n_retries),
                    NULL);
```

**Comment by darosior** [comment]
Added a commit, if you don't mind i didn't feel to resolve YA rebase conflict :/

File: esplora.c (hunk 1 above)
Comment (vincenzopalazzo) [reply esplora.c:101]: >there are not enough transactions made on testnet and bitcoind fee estimation buckets can not be filled.

I reproduced this bug also on mainet with esplora, for this reason, I use a time estimation more bit in  #26. Any way :-) I need more time to understand the cause of the estimation fee error. Thanks to fix this :-)

**Comment by lvaccaro** [comment]
nice, it looks good to me.

Could you run clang-format ? https://travis-ci.org/github/lvaccaro/esplora_clnd_plugin/builds/722574835

**Comment by vincenzopalazzo** [comment]
>lol, passing it as string actually fixed it.... Guess it's a bug report for lightningd then!

@darosior I noted too that lightningd ignore type different to string! I can look inside the lightningd if you don't fixed already it!

>nice, it looks good to me.

@lvaccaro 2 hacks https://github.com/lvaccaro/esplora_clnd_plugin/commit/d007a4515d951237109e3ed976a5313207feeac8 :-)

File: esplora.c (hunk 1 above)
Comment (darosior) [reply esplora.c:101]: Yeah, this one is because the backend for blockstream.info needs to update fee estimations on migrations. See the discussion with shesek here http://gnusha.org/c-lightning/2020-08-28.log

**Comment by darosior** [comment]
> Could you run clang-format ? https://travis-ci.org/github/lvaccaro/esplora_clnd_plugin/builds/722574835

Yeah i know i'm bothering you with my tabs :p. But that's kind of the point of half the commits of this PR: slowly move to tabs instead. Don't you think it's cleaner this way than with a 2-spaces indentation ?

I expect to do more such reformatting and cleanups in the future, just did not want to impose a big diff in this PR. What about changing the clang-format config to use [more conventional settings for the C language](https://github.com/ElementsProject/lightning/blob/master/doc/STYLE.md#care-and-feeding-of-your-fellow-coders) ?

**Comment by lvaccaro** [comment]
ack d53fa0567f297c18e48a592017f109efdd4ab59a

Yeah, I agree. Actually Travis fails but https://github.com/lvaccaro/esplora_clnd_plugin/pull/31 should fix it. 
I like PR linter validation, and I am ok to have a big linter commit, but in another PR, this is so good.
